management:
  security:
     enabled: false

spring:
  datasource:
    url: jdbc:h2:./user_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /user_db